- Fix for reconnection to Slack server and not dropping messages.
ipa320/slack-ros-pkg pull request #4
Opened 2017-07-18 15:25 UTC by souravran

My idea here is to not drop any messages due to connection loss to the slack server. In this PR, along with reconnection functionality, I have added a buffer that would grab all the subscribed messages in case there is no established connection. Once connection resumes, stored messages will be sent to the slack channel.

2017-07-19 12:26 UTC, floweisshardt requested changes

2017-07-19 12:26 UTC, ipa-fmw commented on slack_ros/scripts/slack_ros.py
> +        self.subscribed_msg_store = []
there should be no need to save messages in a queue ourselves. ROS subscriber (with queue size) will handle that for us. we just have to block the callback method until we've reconnected to the slack service. ROS will not execute callbacks in parallel but sequentially as soon as the subscriber callback finished. Thus this is exactly the behaviour we're looking for.

Please use a configurable queue size and remove ```subscribed_msg_store```

2017-07-20 07:05 UTC, souravran commented on slack_ros/scripts/slack_ros.py
> +        self.subscribed_msg_store = []
My initial idea was exactly the same as it has been described above, but I could not find a way to block the callback. One way is to unsubscribe/resubscribe and that's not really blocking the callback, and again whether that is efficient is questionable. Or use semaphore inside the callback method itself, I have not tried this and don't know if threads would go to sleep while blocking the callback.

Any idea is welcome, meanwhile I would further look into this and update the PR.

2017-08-10 13:38 UTC, ipa-bnm commented on slack_ros/scripts/slack_ros.py
> +        self.subscribed_msg_store = []
You could use a condition variable for this. Just wait/block inside the topic callback until the condition is fulfilled (connected to slack). https://docs.python.org/2/library/threading.html
With this kind of implementation you need some kind of connectivity check routine.

On the other side. Creating a separate queue like you did isn't that wrong. As long as there are elements within the queue you can try sending them. If an error during sending happens you can try reconnect and leave the element inside the queue as long as the connection problems appears...

@ipa-fmw what do you think?

2018-09-05 21:34 UTC, fmessmer commented
wont merge...this package is no longer used

2018-09-05 21:34 UTC, closed without merging